name: CI

on:
  push:
  pull_request:
    branches: 
      - main
      - v13

jobs:
  build:
    name: Build ts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run typescript
        run: tsc
